### ISSUE TITLE
ClangFormat file

### ISSUE THREAD

**Issue by siredmar** [stwe/MDCII#11]
I propose putting a clangformat file in the repository. My IDE wants to format the source differently than yours. Making changes this way is nearly impossible.

**Comment by stwe** [comment]
i will do it asap...

**Comment by siredmar** [comment]
cool! thx!

**Comment by siredmar** [comment]
Is the code now formatted with the current clang-format file or do you mind formatting the code with it with another commit?

**Comment by stwe** [comment]
I've already done that. There are a few third-party files that I left out (ImGui/Eventpp/json.hpp/stb_image.h). So normally your IDE should have nothing to complain about. I did that with the latest CLion. For info. which IDE are you using?

**Comment by siredmar** [comment]
I'm using vscode with several extension.
