### ISSUE TITLE
Image failed to load at path: resources/atlas/sgfx/0.png

### ISSUE THREAD

**Issue by siredmar** [stwe/MDCII#14]
Trying to build and run the current `instancing` branch (b3fdef55311128a8a5f222b07124ac310cb1eedc) and getting this error message on startup:

```
[22:59:14] MDCII: MdciiException occurred: 
[Message]: [TileAtlas::LoadAtlasImages()] Image failed to load at path: resources/atlas/sgfx/0.png
[File]: /home/armin/dev/MDCII/src/map/TileAtlas.cpp
[Line]: 99
```

**Comment by stwe** [comment]
To start the program, so-called tile atlas graphics are required, which are not distributed and are therefore not in the repository. As of today, the files can only be created with Benno4j.

**Comment by stwe** [comment]
It is planned to provide a small Java tool to create the atlas files. The code is already ready in Benno4j.
