### ISSUE TITLE
Bug: Mouse picker has x,y offset after zooming out and in again

### ISSUE THREAD

**Issue by siredmar** [stwe/MDCII#22]
After zooming back and forth the mouse picker has an x,y offset. This is still the case after going back to the main menu and starting a new game.

**Comment by stwe** [comment]
Is this also the case if you activate the `Select on terrain` checkbox?

![select](https://user-images.githubusercontent.com/2964748/212149437-57e670c9-a2d4-49f2-81aa-2926456a9c96.png)
