### ISSUE TITLE
Build without conan

### ISSUE THREAD

**Issue by siredmar** [stwe/MDCII#26]
Hi!

It seems that recently you removed conan from the project. I don't quite understand what you mean by
```
Compiling MDCII
I prefer vcpkg. You can install it as described here.

Now the Requirements have to be installed.
```

I'm not familiar with vcpkg. Could you give any hints on using this and how to build MDCII?

Further i'm getting errors that glew could not be found on ubuntu 22.04
Did you change anything in CMake files?

**Comment by stwe** [comment]
Yes, the CMake files have been adapted to Vcpkg. The new release of Conan with version 2.0 blew up my whole package management. Everything has changed and there is no more support for premake. The documentation is incomplete. Vcpkg is much simpler and works just fine. Disadvantage is that I can't install packages with a specific version, so I had to adapt everything to the new ImGui. I'll write a guide for a build with vcpkg as soon as possible.
