### ISSUE TITLE
vcpkg build env (package versions, ...)

### ISSUE THREAD

**Issue by siredmar** [stwe/MDCII#29]
I have struggles compiling the dependencies mentioned in the Readme. 
After installing protobuf, it complains that files are generated using an older version. 
Would you mind adding a `vcpkg.json` with all dependencies pinned down to the versions you are using?

A working make target would also be great as i am struggling very hard to get this compiled at all `*sad face`*

**Comment by stwe** [comment]
OK. That's the problem with C++. Normally you can install the latest version of Protobuf. The files `/src/cod.pb.cc` and `/src/cod.pb.h` were probably created with an older version. You have to recreate them with Protoc. Check this out:
[Compiling Your Protocol Buffers](https://protobuf.dev/getting-started/cpptutorial/)
It's been a really long time since I did this.

**Comment by siredmar** [comment]
> OK. That's the problem with C++. Normally you can install the latest version of Protobuf. The files `/src/cod.pb.cc` and `/src/cod.pb.h` were probably created with an older version. You have to recreate them with Protoc. Check this out: [Compiling Your Protocol Buffers](https://protobuf.dev/getting-started/cpptutorial/) It's been a really long time since I did this.

Yeah, this is why i'm porting my codebase to golang 😄
I'm currently working on the render. Once this is done, i'm basically at the same stage as with my C++ project.

**Comment by stwe** [comment]
If you want to take code from my project, here's a tip: Take a look at my source code in the IsoSandbox repo. The code simply represents a flat isometric surface on which roads can be built. The roads also align themselves during construction. This isn't possible in MDCII at the moment, as the code is a bit buggy. So if you're working on the map or camera or the mouse picker, take a look at the (clean) code in the sandbox first. You have access to the private repo. I can also send you the assets, although everything should be self-explanatory.

**Comment by stwe** [comment]
https://github.com/stwe/MDCII/commit/398704c826874660e1eed471e07ad44bec491bc6

**Comment by siredmar** [comment]
The problem aren't the proto generated files. They can easily be generated with the protoc provided by vcpkg. The problem are all dependencies and their versions. After installing dependencies via vcpkg compilation failed because of completely different versions used in your project and what vcpkg installed. There is a way using the `vcpkg.json` and `dependencies` with `overrides` to pin down dependencies versins. 
Would you mind adding this file. I guess it should look something like this (but with modified versions)

```
{
  "name": "mdcii",
  "version": "0.0.1",
  "description": "mdcii",
  "dependencies": [
    {
      "name": "vcpkg-cmake",
      "host": true
    },
    {
      "name": "vcpkg-cmake-config",
      "host": true
    },
    "gettext-libintl",
    "spdlog",
    "imgui",
    "protobuf",
    "abseil"
  ],
  "builtin-baseline":"c82f74667287d3dc386bce81e44964370c91a289",
  "overrides": [
    {
      "name": "gettext-libintl",
      "version": "0.22.51"
    },
    {
      "name": "spdlog",
      "version": "1.41.1"
    },
    {
      "name": "imgui",
      "version": "1.91.0"
    },
    {
      "name": "protobuf",
      "version": "4.25.1"
    },
    {
      "name": "abseil",
      "version": "20240722.0"
    }
  ]
}
```

Also i have massive problems with imgui. I installed imgui via vcpkg (like described in the readme). But it collides with the vendored version. In the CMakeLists.txt it tries to find imgui and to link against it. This creates problems on my side.

**Comment by stwe** [comment]
I successfully compiled yesterday with:

```json
{
  "name" : "mdcii",
  "version-string" : "1.0.0",
  "builtin-baseline" : "f176b58f35a75f9f8f54099cd9df97d2e2793a2e",
  "dependencies" : [ {
    "name" : "spdlog",
    "version>=" : "1.14.1"
  }, {
    "name" : "protobuf",
    "version>=" : "4.25.1#1"
  }, {
    "name" : "imgui",
    "version>=" : "1.91.0"
  } ]
}
```
I did not need gettext-libintl on my system via vcpkg. To solve the problems with ImGui and Protobuf, I uploaded updates yesterday. Did you forget to do git pull? If that still doesn't work, please let me know.

**Comment by stwe** [comment]
```bash
FROM ubuntu:22.04

LABEL maintainer="stwe"
LABEL version="main"
LABEL description="This is a Docker Image for MDCII with vcpkg support."

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update
RUN apt install -y \
    build-essential \
    git \
    cmake \
    libglu1-mesa-dev \
    libpng-dev \
    curl \
    zip \
    unzip \
    tar \
    pkg-config \
    ca-certificates \
    libpulse-dev
RUN apt clean -y

# Install vcpkg
WORKDIR /vcpkg
RUN git clone https://github.com/microsoft/vcpkg.git . && \
    ./bootstrap-vcpkg.sh

# Add vcpkg to the PATH environment variable
ENV PATH="/vcpkg:${PATH}"

# Set the default triplet
ENV VCPKG_DEFAULT_TRIPLET=x64-linux

# Install spdlog using vcpkg
RUN ./vcpkg install spdlog protobuf imgui

# Set working directory for the project
WORKDIR /MDCII

# Copying the project
COPY install/ ./install/
COPY resources/ ./resources/
COPY src/ ./src/
COPY CMakeLists.txt .
COPY config.ini .

WORKDIR /MDCII/build

# Build project with cmake and vcpkg
RUN cmake -DCMAKE_TOOLCHAIN_FILE=/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug .. && \
    cmake --build . --parallel 8

# Entry point for the container
ENTRYPOINT [ "/MDCII/build/src/MDCII" ]
```
Compiles and links everything together without errors.

**Comment by siredmar** [comment]
many thanks!
